version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_15
    environment:
      - POSTGRES_USER=zope
      - POSTGRES_PASSWORD=zope
      - POSTGRES_DB=zodb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./etc/postgres/pg_hba.conf:/var/lib/postgresql/conf/pg_hba.conf
    command: postgres -D /var/lib/postgresql/data -c hba_file=/var/lib/postgresql/conf/pg_hba.conf
    networks:
      zms_network:
        aliases:
          - postgres  # Ensure Hostname is reachable
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zope"]
      interval: 5s
      timeout: 5s
      retries: 10

      
  zms5:
    image: zms5:relstorage 
    build:
      context: .
      dockerfile: dockerfile
    container_name: zms5_relstorage
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - CONFIG_FILE=/home/zope/etc/zope.ini
      - INSTANCE_HOME=/home/zope
      - CLIENT_HOME=/home/zope
      - RELSTORAGE_DSN=dbname=zodb user=zope password=zope host=postgres port=5432
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - zms_network
    volumes:
      - zms5_data:/home/zope/var

networks:
  zms_network:
    driver: bridge

volumes:
  postgres_data:
  zms5_data: